[lab5_khadija-ramzi]
name = "project"
version = "0.1.0"
description = "A machine learning project for lab 5 by Khadija Ramzi"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "scikit-learn",
    "xgboost",
    "catboost",
    "shap",
    "joblib",
    "scipy"
]
